const MODALS_DEQUEUE_ALL = 'MODALS_DEQUEUE_ALL'
const MODALS_DEQUEUE_ONE = 'MODALS_DEQUEUE_ONE'
const MODALS_ENQUEUE_ONE = 'MODALS_ENQUEUE_ONE'

export {
  MODALS_DEQUEUE_ALL,
  MODALS_DEQUEUE_ONE,
  MODALS_ENQUEUE_ONE,
}
